export interface ErrorDefinition {
  code: string;
  statusCode: number;
  message: string;
  retryable: boolean;
  retryAfterSeconds: number | null;
}

export const ERROR_REGISTRY: Record<string, ErrorDefinition> = {
  VALIDATION_FAILED: {
    code: "VALIDATION_FAILED",
    statusCode: 400,
    message: "Some fields are missing or invalid.",
    retryable: false,
    retryAfterSeconds: null,
  },
  INVALID_COMMAND_SYNTAX: {
    code: "INVALID_COMMAND_SYNTAX",
    statusCode: 400,
    message: "That command was not understood.",
    retryable: false,
    retryAfterSeconds: null,
  },
  AUTH_REQUIRED: {
    code: "AUTH_REQUIRED",
    statusCode: 401,
    message: "Please join the room again.",
    retryable: false,
    retryAfterSeconds: null,
  },
  SESSION_INVALID: {
    code: "SESSION_INVALID",
    statusCode: 401,
    message: "Your room session expired. Please rejoin.",
    retryable: false,
    retryAfterSeconds: null,
  },
  WEBSOCKET_TOKEN_INVALID: {
    code: "WEBSOCKET_TOKEN_INVALID",
    statusCode: 401,
    message: "Realtime connection could not be authenticated.",
    retryable: false,
    retryAfterSeconds: null,
  },
  INTEGRATION_AUTH_INVALID: {
    code: "INTEGRATION_AUTH_INVALID",
    statusCode: 401,
    message: "Music command integration is not authenticated.",
    retryable: false,
    retryAfterSeconds: null,
  },
  FORBIDDEN: {
    code: "FORBIDDEN",
    statusCode: 403,
    message: "You are not allowed to do that.",
    retryable: false,
    retryAfterSeconds: null,
  },
  HOST_REQUIRED: {
    code: "HOST_REQUIRED",
    statusCode: 403,
    message: "Only the host can do that.",
    retryable: false,
    retryAfterSeconds: null,
  },
  MODERATOR_REQUIRED: {
    code: "MODERATOR_REQUIRED",
    statusCode: 403,
    message: "Only a host or moderator can do that.",
    retryable: false,
    retryAfterSeconds: null,
  },
  MUTED: {
    code: "MUTED",
    statusCode: 403,
    message: "You are muted in this room.",
    retryable: false,
    retryAfterSeconds: null,
  },
  BANNED: {
    code: "BANNED",
    statusCode: 403,
    message: "You cannot participate in this room.",
    retryable: false,
    retryAfterSeconds: null,
  },
  ROOM_NOT_FOUND: {
    code: "ROOM_NOT_FOUND",
    statusCode: 404,
    message: "Room not found.",
    retryable: false,
    retryAfterSeconds: null,
  },
  QUEUE_ITEM_NOT_FOUND: {
    code: "QUEUE_ITEM_NOT_FOUND",
    statusCode: 404,
    message: "That queue item was not found.",
    retryable: false,
    retryAfterSeconds: null,
  },
  TRACK_NOT_FOUND: {
    code: "TRACK_NOT_FOUND",
    statusCode: 404,
    message: "That track was not found.",
    retryable: false,
    retryAfterSeconds: null,
  },
  CHAT_MESSAGE_NOT_FOUND: {
    code: "CHAT_MESSAGE_NOT_FOUND",
    statusCode: 404,
    message: "That chat message was not found.",
    retryable: false,
    retryAfterSeconds: null,
  },
  NICKNAME_TAKEN: {
    code: "NICKNAME_TAKEN",
    statusCode: 409,
    message: "Someone is already using that nickname in this room.",
    retryable: false,
    retryAfterSeconds: null,
  },
  NICKNAME_PROTECTED: {
    code: "NICKNAME_PROTECTED",
    statusCode: 409,
    message: "That nickname is protected. Enter its password to use it.",
    retryable: false,
    retryAfterSeconds: null,
  },
  NICKNAME_PASSWORD_INCORRECT: {
    code: "NICKNAME_PASSWORD_INCORRECT",
    statusCode: 403,
    message: "That nickname is protected. The password was incorrect.",
    retryable: false,
    retryAfterSeconds: null,
  },
  NICKNAME_PASSWORD_RATE_LIMITED: {
    code: "NICKNAME_PASSWORD_RATE_LIMITED",
    statusCode: 429,
    message: "Too many incorrect attempts. Try again later.",
    retryable: true,
    retryAfterSeconds: null,
  },
  ROOM_PASSWORD_REQUIRED: {
    code: "ROOM_PASSWORD_REQUIRED",
    statusCode: 401,
    message: "This room requires a password.",
    retryable: false,
    retryAfterSeconds: null,
  },
  ROOM_PASSWORD_INCORRECT: {
    code: "ROOM_PASSWORD_INCORRECT",
    statusCode: 403,
    message: "Room password was incorrect.",
    retryable: false,
    retryAfterSeconds: null,
  },
  QUEUE_LOCKED: {
    code: "QUEUE_LOCKED",
    statusCode: 403,
    message: "The host has locked song additions.",
    retryable: false,
    retryAfterSeconds: null,
  },
  CHAT_LOCKED: {
    code: "CHAT_LOCKED",
    statusCode: 403,
    message: "Chat is locked right now.",
    retryable: false,
    retryAfterSeconds: null,
  },
  SONG_REQUEST_COOLDOWN: {
    code: "SONG_REQUEST_COOLDOWN",
    statusCode: 429,
    message: "You can request another song after the cooldown.",
    retryable: true,
    retryAfterSeconds: null,
  },
  MAX_PENDING_PER_USER_REACHED: {
    code: "MAX_PENDING_PER_USER_REACHED",
    statusCode: 409,
    message: "Wait until one of your songs resolves before adding another.",
    retryable: false,
    retryAfterSeconds: null,
  },
  QUEUE_FULL: {
    code: "QUEUE_FULL",
    statusCode: 409,
    message: "The queue is full right now.",
    retryable: false,
    retryAfterSeconds: null,
  },
  VIDEO_URL_INVALID: {
    code: "VIDEO_URL_INVALID",
    statusCode: 400,
    message: "Enter a valid YouTube video URL.",
    retryable: false,
    retryAfterSeconds: null,
  },
  VIDEO_UNAVAILABLE: {
    code: "VIDEO_UNAVAILABLE",
    statusCode: 422,
    message: "This video cannot be played here. Try another YouTube link.",
    retryable: false,
    retryAfterSeconds: null,
  },
  VIDEO_TOO_LONG: {
    code: "VIDEO_TOO_LONG",
    statusCode: 422,
    message: "This video is longer than the room limit.",
    retryable: false,
    retryAfterSeconds: null,
  },
  DUPLICATE_VIDEO: {
    code: "DUPLICATE_VIDEO",
    statusCode: 409,
    message: "That song is already in the queue.",
    retryable: false,
    retryAfterSeconds: null,
  },
  YOUTUBE_METADATA_DEGRADED: {
    code: "YOUTUBE_METADATA_DEGRADED",
    statusCode: 503,
    message: "YouTube metadata is temporarily limited. The song may be queued with partial details.",
    retryable: true,
    retryAfterSeconds: null,
  },
  VOTE_NOT_ALLOWED: {
    code: "VOTE_NOT_ALLOWED",
    statusCode: 403,
    message: "You cannot vote on this item.",
    retryable: false,
    retryAfterSeconds: null,
  },
  MECHANIC_CHANGE_COOLDOWN: {
    code: "MECHANIC_CHANGE_COOLDOWN",
    statusCode: 429,
    message: "Playlist mode was changed recently. Try again later.",
    retryable: true,
    retryAfterSeconds: null,
  },
  LISTENER_READ_ONLY: {
    code: "LISTENER_READ_ONLY",
    statusCode: 403,
    message: "Join with a protected nickname to do that.",
    retryable: false,
    retryAfterSeconds: null,
  },
  NICKNAME_PROTECTION_REQUIRED: {
    code: "NICKNAME_PROTECTION_REQUIRED",
    statusCode: 409,
    message: "A protected nickname is required to participate in this room.",
    retryable: false,
    retryAfterSeconds: null,
  },
  RATE_LIMITED: {
    code: "RATE_LIMITED",
    statusCode: 429,
    message: "You're doing that too quickly. Try again shortly.",
    retryable: true,
    retryAfterSeconds: null,
  },
  DEPENDENCY_UNAVAILABLE: {
    code: "DEPENDENCY_UNAVAILABLE",
    statusCode: 503,
    message: "A required service is temporarily unavailable.",
    retryable: true,
    retryAfterSeconds: null,
  },
  SERVICE_DEGRADED: {
    code: "SERVICE_DEGRADED",
    statusCode: 503,
    message: "Trackstacc is running in degraded mode. Try again shortly.",
    retryable: true,
    retryAfterSeconds: null,
  },
  INTERNAL_ERROR: {
    code: "INTERNAL_ERROR",
    statusCode: 500,
    message: "Something went wrong. Try again.",
    retryable: true,
    retryAfterSeconds: null,
  },
};

export function getErrorDefinition(code: string): ErrorDefinition {
  return ERROR_REGISTRY[code] ?? ERROR_REGISTRY["INTERNAL_ERROR"]!;
}
